version: "3"
services:
  # Application & web server
  app:
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - "database"
    ports:
      - 8080:80
      - 443:443

  # Database
  database:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3304:3304"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - database:db
    depends_on:
      - database
    ports:
      - 8082:80
